#변수 지정(assign variable)
x <- c(1,2,4)
q <- c(x,x,8)

#변수 출력 및 접근(printing the variable and access to the variable)
x
cat(x)
x[3]

#변수의 열에 접근(access to part of an array)
x <- c(1,2,4)
x[2:3]

#간단한 함수들(simple functions)
mean(x) #평균
sd(x) #표준편차
summary(x) #간단한 통계 및 요약

y <- mean(x)
y # print y
[1] 2.333333
#이후는 주석(comment)으로 R은 이를 무시한다.

mean(Nile)
sd(Nile)
hist(Nile)

#Objects
#vectors
x<-c(1,2,3)
length(x) #벡터의 길이
y<-seq(from = 3, to =5, by=1) #seq함수를 이용한 생성
x+y	#벡터간 덧셈(addition by component) / x*y	#벡터간 곱셈(Multiplication by component) 
y[y<5]	#조건으로 벡터 접근(boolean/logical)
rep(3,5) #벡터를 반복하여 벡터 생성(repeated generation of vectors)

#문자열(string)
y <- "abc"
y
mode(y)

#행렬(Matrtix)
y <- matrix(c(1,2,3,4),nrow=2,ncol=2)  #행렬 생성(creating Matrix)
m <- rbind(c(1,4), c(2,2)) #rbind는 열을 기준으로 묶어주는 함수 (bind by rows)
m %*% c(1,1) #행렬의 곱셈 (Matrix multplication)
m * m
m%*%m
m[1,2]
m[2,2]
m[1,]
m[,2]
m[,-2]
colnames() # column 이름(name of columns)
rownames() # row 이름(name of rows)

#list
x <- list(u=2, v="abc")
x
x$u

hn <- hist(Nile,plot=FALSE)
print(hn)

#데이터 프레임(Dataframe)

d <- data.frame(list(kids=c("Jack","Jill"),ages=c(12,10)))
d
head(USarrests)	#앞부분의 데이터를 보여준다 (shows first few rows of data)
summary(USarrests)	#데이터의 간략한 설명 (summary statistic of the data)

#함수 및 패키지
a<-function(x,y,z){(x+y+z)/3}; a(3,2,6)	#사용자가 직접 만든함수
install.packages("MASS")
library(MASS)
?lda

#데이터 파일 인풋 (Data file input)
getwd()
setwd("C:\Users\seokho\Documents\R")

z <- read.table("Ozone.txt", header=TRUE)
z <- read.table("Ozone.csv", header=TRUE,sep= ',') 

write.table(a,"xcnew.csv",row.names=FALSE,col.names=FALSE,sep=",")

attach(iris)
#######################################################################################################################
#Graphics in R

#plot 함수

plot(c(1,2,3), c(1,2,4))	# 산점도 (scatter plot)
plot(c(-3,3), c(-1,5), type = "n", xlab="x", ylab="y") #type옵션에 따라 그래프 형태 결정 (plot type is determined by type option)

#abline, line, points, hist 함수

x <- c(1,2,3)
y <- c(1,3,8)
plot(x,y)
abline(0, 1,col='red')
lines(c(1.5,2.5, 3),c(3,3, 2),col='blue')


library(MASS)
data(hills)
attach(hills)
plot(climb, time)


abline(lm(time~climb), col="red")
lines(lowess(climb, time), col="blue")

data(faithful)
attach(faithful)
hist(eruptions, breaks=seq(1.6, 5.2, 0.2), prob=TRUE)
lines(density(eruptions, bw=0.1))
rug(eruptions)

testscores = data.frame(Exam1 = rnorm(100, 75, 15) , Exam2 = rnorm(100, 70, 20))
d1 = density(testscores$Exam1,from=0,to=100)
d2 = density(testscores$Exam2,from=0,to=100)
plot(d1,main="",xlab="",col='red')
lines(d2,col='blue')

hist(x)
x11()
hist(y)
plot(testscores$Exam1,testscores$Exam3)
points(c(80,90), c(85, 90), pch="+",lwd=5, col='red')

#legend
library(sm)
mhills = data.frame(time=hills$time, dist=hills$dist*1.60934, climb=hills$climb*0.3048)# change mile to km, feet to m
lmhills = log(mhills)
attach(lmhills)
climbf = cut(climb, breaks=c(4.5, 5.5, 6.5, 7.8),
             labels=c("low", "med", "high"))
sm.density.compare(time, climbf, lty=rep(1,3), col=1:3)
legend(x=5, y=0.8, legend = levels(climbf), fill=1:3)
detach(lmhills)

#Curve
g <- function(t)  { return (t^2+1)^0.5 }
x <- seq(0,5,length=10000)
y <- g(x)
plot(x,y,type="l")

curve((x^2+1)^0.5,0,5)
curve((x+1)^0.5,0,5, add=T)

f <- function(x) return((x^2+1)^0.5)
plot(f,0,5)

##########################################################################################################
#ggplot2 by Hadley Wickham

install.packages(c("ggplot2" , "dplyr"))
library(ggplot2)	# 패키지 로딩
library(dplyr)	# 데이터를 다루는 dplyr 패키지


#빌드업 (structure)
p1<-ggplot(mpg, aes(x=displ, y= hwy)) + geom_point() #mpg 예시
p1

#aes options
ggplot(mpg, aes(x=displ, y= hwy, colour=class)) + geom_point()	 
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()
p

ggplot(mpg, aes(x=displ, y= hwy, shape=drv)) + geom_point()
ggplot(mpg, aes(x=displ, y= hwy, size=cyl)) + geom_point()


#facet options
ggplot(mpg, aes(displ, hwy)) + geom_point() + facet_wrap(~class)
ggplot(mpg, aes(displ, hwy)) + geom_point() + facet_wrap(~class,nrow=2,ncol=4)

p1+facet_grid(drv ~.)
p1+facet_grid(drv ~ cyl)
p1+facet_grid(drv ~ cyl, margin = T)

# Save graphs
pdf("output1.pdf", width = 6, height = 6)
ggplot(mpg, aes(displ, cty)) +
  geom_point()
dev.off()

ggplot(mpg, aes(displ, cty)) + geom_point()
ggsave("output2.pdf")

# Example of Linear Model
# create and summarise model
cars.model <- lm(dist ~ speed, data = cars)
summary(cars.model) 

# add 'fit', 'lwr', and 'upr' columns to dataframe (generated by predict)
cars.predict <- cbind(cars, predict(cars.model, interval = 'confidence'))

# plot the points (actual observations), regression line, and confidence interval
p <- ggplot(cars.predict, aes(speed,dist)) 
p <- p + geom_point()
p <- p + geom_line(aes(speed, fit))
p <- p + geom_ribbon(aes(ymin=lwr,ymax=upr), alpha=0.3)
p

